import{S as b,i as c}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();async function L(r,o){const a="51425733-ebfe71f47e07541f439d053d0",s="https://pixabay.com/api/",e=new URLSearchParams({key:a,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:15}),t=await fetch(`${s}?${e}`);if(!t.ok)throw new Error("Error fetching images");return await t.json()}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more");let v=new b(".gallery a");function w(r){const o=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:t,views:n,comments:p,downloads:g})=>`
    <li class="gallery-item">
      <a href="${s}"><img src="${a}" alt="${e}" loading="lazy" /></a>
      <div class="info">
       <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${n}</p>
        <p><b>Comments:</b> ${p}</p>
        <p><b>Downloads:</b> ${g}</p>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",o),v.refresh()}function S(){f.innerHTML=""}function q(){m.classList.add("is-visible")}function $(){m.classList.remove("is-visible")}function B(){y.classList.add("is-visible")}function l(){y.classList.remove("is-visible")}const E=document.querySelector(".form"),P=document.querySelector('input[name="search-text"]'),M=document.querySelector(".load-more");let u="",i=1,d=0;E.addEventListener("submit",async r=>{if(r.preventDefault(),u=P.value.trim(),!u){c.error({message:"Please enter a search query!"});return}i=1,S(),l(),await h()});M.addEventListener("click",async()=>{i++,await h()});async function h(){try{q();const r=await L(u,i);if(d=r.totalHits,r.hits.length===0&&i===1){c.info({message:"Sorry, there are no images matching your search query. Please try again!"}),l();return}if(w(r.hits),i*15>=d?(l(),c.info({message:"We're sorry, but you've reached the end of search results."})):B(),i>1){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}catch{c.error({message:"Error fetching images, please try again later."})}finally{$()}}
//# sourceMappingURL=index.js.map
