import{a as L,S as v,i as c}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const f=15;async function w(r,o){const a="51425733-ebfe71f47e07541f439d053d0",s="https://pixabay.com/api/",e={key:a,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:f};try{return(await L.get(s,{params:e})).data}catch{throw new Error("Error fetching images")}}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more");let q=new v(".gallery a");function S(r){const o=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:t,views:i,comments:g,downloads:b})=>`
    <li class="gallery-item">
      <a href="${s}"><img src="${a}" alt="${e}" loading="lazy" /></a>
      <div class="info">
       <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${i}</p>
        <p><b>Comments:</b> ${g}</p>
        <p><b>Downloads:</b> ${b}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",o),q.refresh()}function E(){m.innerHTML=""}function P(){y.classList.add("is-visible")}function B(){y.classList.remove("is-visible")}function $(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}const M=document.querySelector(".form"),O=document.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more");let u="",n=1,d=0;M.addEventListener("submit",async r=>{if(r.preventDefault(),u=O.value.trim(),!u){c.error({message:"Please enter a search query!"});return}n=1,E(),l(),await p()});x.addEventListener("click",async()=>{l(),n++,await p()});async function p(){try{P();const r=await w(u,n);if(d=r.totalHits,r.hits.length===0&&n===1){c.info({message:"Sorry, there are no images matching your search query. Please try again!"}),l();return}if(S(r.hits),n*f>=d?(l(),c.info({message:"We're sorry, but you've reached the end of search results."})):$(),n>1){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}catch{c.error({message:"Error fetching images, please try again later."})}finally{B()}}
//# sourceMappingURL=index.js.map
