import{a as b,S as L,i as c}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();async function v(r,o){const i="51425733-ebfe71f47e07541f439d053d0",n="https://pixabay.com/api/",t={key:i,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};try{return(await b.get(n,{params:t})).data}catch{throw new Error("Error fetching images")}}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more");let w=new L(".gallery a");function E(r){const o=r.map(({webformatURL:i,largeImageURL:n,tags:e,likes:t,views:s,comments:p,downloads:g})=>`
    <li class="gallery-item">
      <a href="${n}"><img src="${i}" alt="${e}" loading="lazy" /></a>
      <div class="info">
       <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${p}</p>
        <p><b>Downloads:</b> ${g}</p>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",o),w.refresh()}function P(){f.innerHTML=""}function q(){m.classList.add("is-visible")}function S(){m.classList.remove("is-visible")}function B(){y.classList.remove("is-hidden")}function l(){y.classList.add("is-hidden")}const $=document.querySelector(".form"),A=document.querySelector('input[name="search-text"]'),M=document.querySelector(".load-more");let u="",a=1,d=0;const _=8;$.addEventListener("submit",async r=>{if(r.preventDefault(),u=A.value.trim(),!u){c.error({message:"Please enter a search query!"});return}a=1,P(),l(),await h()});M.addEventListener("click",async()=>{l(),a++,await h()});async function h(){try{q();const r=await v(u,a);if(d=r.totalHits,r.hits.length===0&&a===1){c.info({message:"Sorry, there are no images matching your search query. Please try again!"}),l();return}if(E(r.hits),a*_>=d?(l(),c.info({message:"We're sorry, but you've reached the end of search results."})):B(),a>1){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}catch{c.error({message:"Error fetching images, please try again later."})}finally{S()}}
//# sourceMappingURL=index.js.map
